# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
# development:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: goldenowl_development
#   pool:     5
#   template: template0

# test:
#   adapter:  postgresql
#   host:     localhost
#   encoding: unicode
#   database: goldenowl_test
#   pool:     5
#   template: template0

default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: postgres
  host: localhost
  pool: 5

development:
  <<: *default
  database: goldenowl_development
